baseurl = "https://www.innnblog.com/"
languageCode = "en-US"
title = "Innnnnnnnnnn"
# Enable comments by entering your Disqus shortname
#disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-39295142-1"
theme = "hugo-sustain"
disableHugoGeneratorInject = true
#publishDir = "docs"
[permalinks]
  blog = "/:year/:month/:slug"

[params]
  avatar = "ava.jpg"
  author = "Sarat Limawongpranee"
  description = "Thai Blog Diary"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Email         = "saratlim@gmail.com"
  Twitter       = "innneang"


## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "/blog/"
[[menu.main]]
  name = "archived"
  weight = 100
  identifier = "blog"
  url = "/archived/"
# [[menu.main]]
#   name = "projects"
#   identifier = "projects"
#   weight = 200
#   url = "/projects/"
[[menu.main]]
   name = "About"
   identifier = "About"
   weight = 300
   url = "/about/"
